@startuml
title Meetup Selector Use Cases

left to right direction

:User: as User
:Logged User: as LoggedUser
:Administrator: as Admin

rectangle MeetupSelector {
	package Talks {
		usecase TALK_UC0 as "View all Talks"
		usecase TALK_UC1 as "Add a Talk"
		usecase TALK_UC2 as "Add a Speaker"
		usecase TALK_UC3 as "Update their talk"
		usecase TALK_UC4 as "Delete a talk"
	}
	package Proposals {
		usecase PROPOSAL_UC0 as "View all Proposals"
		usecase PROPOSAL_UC1 as "Add a Proposal"
		usecase PROPOSAL_UC2 as "Vote for a Proposal"
		usecase PROPOSAL_UC3 as "Remove the vote for a Proposal"
		usecase PROPOSAL_UC4 as "Select a Proposal for
		creating an Event"
	}
	package Events {
		usecase EVENT_UC0 as "View all Events"
		usecase EVENT_UC1 as "Create an Event"
	}
}

User <|-- LoggedUser
LoggedUser <|-- Admin

User --> TALK_UC0
User --> PROPOSAL_UC0
User --> EVENT_UC0

LoggedUser --> TALK_UC1
LoggedUser --> TALK_UC2
LoggedUser --> TALK_UC3
LoggedUser --> PROPOSAL_UC1
LoggedUser --> PROPOSAL_UC2
LoggedUser --> PROPOSAL_UC3

Admin --> TALK_UC4
Admin --> PROPOSAL_UC4
Admin --> EVENT_UC1

@enduml
