# Generated by Django 3.2.16 on 2022-10-14 18:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protected', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('headline', models.CharField(max_length=255, verbose_name='headline')),
                ('description', models.TextField(verbose_name='description')),
                ('duration', models.DurationField(verbose_name='duration')),
                ('type', models.CharField(choices=[('T', 'talk'), ('W', 'workshop'), ('K', 'kata')], default='T', max_length=1, verbose_name='type')),
                ('difficulty', models.CharField(choices=[('E', 'easy'), ('M', 'medium'), ('H', 'hard')], default='E', max_length=1, verbose_name='difficulty')),
                ('slides', models.URLField(blank=True, null=True, verbose_name='slides')),
                ('repository', models.URLField(blank=True, null=True, verbose_name='repository')),
            ],
            options={
                'verbose_name': 'talk',
                'verbose_name_plural': 'talks',
            },
        ),
    ]
