# Generated by Django 3.2.16 on 2022-10-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0003_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='talks', to='talks.Speaker', verbose_name='speakers'),
        ),
    ]
