# Generated by Django 3.2.16 on 2022-10-24 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='Language',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='topic',
            new_name='topics',
        ),
    ]
