# Generated by Django 3.2.16 on 2022-11-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_auto_20221101_1033"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="GDPR_accepted",
            field=models.BooleanField(default=False, verbose_name="GDPR_accepted"),
        ),
    ]
